# Generated by Django 3.0.4 on 2020-03-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_adress', models.CharField(max_length=255)),
                ('firm_phone', models.CharField(max_length=255)),
                ('year_count', models.IntegerField()),
                ('working_hours', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('stars_count', models.IntegerField()),
                ('pool', models.BooleanField(default=False)),
                ('bar_free', models.BooleanField(default=False)),
                ('beach', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('tour_start', models.DateTimeField()),
                ('tour_finish', models.DateTimeField()),
                ('departure_point', models.CharField(max_length=40)),
                ('prise', models.IntegerField()),
                ('country', models.CharField(max_length=40)),
                ('count_of_free_place', models.IntegerField()),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Firm')),
            ],
        ),
    ]
