# Generated by Django 3.0.4 on 2020-03-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200306_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_phone',
            field=models.CharField(default='', max_length=255, verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firm',
            name='firm_mail',
            field=models.EmailField(max_length=254, verbose_name='Почта фирмы'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_mail',
            field=models.EmailField(max_length=254, verbose_name='Почта отеля'),
        ),
    ]
