# Generated by Django 3.0.4 on 2020-03-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20200306_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='', max_length=40, verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
