# Generated by Django 3.0.4 on 2020-03-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_hotel_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255, unique=True, verbose_name='Название Статьи')),
                ('photo', models.IntegerField(verbose_name='Фото статьи')),
                ('note', models.TextField(verbose_name='Содержание статьи')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Firm', verbose_name='Компания'),
        ),
    ]
