# Generated by Django 3.0.4 on 2020-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20200308_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото статьи'),
        ),
    ]
