# Generated by Django 3.0.4 on 2020-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_auto_20200308_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='photos', verbose_name='Фото статьи'),
        ),
    ]
