# Generated by Django 3.0.4 on 2020-03-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20200308_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='data',
        ),
        migrations.RemoveField(
            model_name='article',
            name='note',
        ),
    ]
