# Generated by Django 3.0.4 on 2020-03-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20200311_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(default='', upload_to='photos', verbose_name='Фото статьи'),
            preserve_default=False,
        ),
    ]
