# Generated by Django 3.0.4 on 2020-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20200315_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='photo',
            field=models.ImageField(default=' ', upload_to='photos', verbose_name='Фото статьи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(default='', upload_to='photos', verbose_name='Фото статьи'),
            preserve_default=False,
        ),
    ]
