# Generated by Django 3.0.4 on 2020-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_auto_20200316_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tour_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
