# Generated by Django 3.0.4 on 2020-03-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_auto_20200318_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='hotel',
            new_name='tour',
        ),
    ]
