# Generated by Django 3.0.4 on 2020-03-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_auto_20200318_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tours.Tour', verbose_name='Тур'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tours.Hotel', verbose_name='Отель'),
            preserve_default=False,
        ),
    ]
