# Generated by Django 3.0.4 on 2020-03-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_remove_order_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tours.Tour', verbose_name='Тур'),
            preserve_default=False,
        ),
    ]
